# coding: utf-8

"""
    SOA Buoi 7 – Product API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.products_api import router as ProductsApiRouter

app = FastAPI(
    title="SOA Buoi 7 – Product API",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="1.0.0",
)

app.include_router(ProductsApiRouter)
